### ISSUE TITLE
Support for iOS <11.0

### ISSUE THREAD

**Issue by VaughnGH** [louisdh/terminal#1]
Hello, there are many of us out there who still use iOS 10 or earlier, would it be possible to add legacy support to this app? (The App Store warns that this app is only compatible with iOS 11.0+)

**Comment by louisdh** [comment]
I'm gonna keep this project iOS 11.0+ because that makes it 64 bit (arm64) only. That way I don't have to worry about different architectures.

**Comment by tbodt** [comment]
You can make the app 64-bit only and still support iOS 10.

**Comment by louisdh** [comment]
@tbodt Good point. 
This project does use the new Asset Catalog colors, which requires iOS 11.
Regarding 64-bit: Supporting iOS 10 and requiring 64-bit will still make the app unavailable for some users. As a matter of fact, having a 32-bit device might be the #1 reason some users are staying on iOS 10. So I'm gonna keep the project iOS 11.0+.
