### ISSUE TITLE
How to find your Installation Time, Date ??

### ISSUE THREAD

**Issue by Basic-income** [louisdh/terminal#100]
Hello I use openterm on iPhone X and iPad 9.7 with iOS 11.2.6.

But how to find your Installation Date?

**Comment by louisdh** [comment]
I don't understand what you mean by "Installation Date", can you explain please?

**Comment by Basic-income** [comment]
@louisdh 
thats what I meant
https://www.tekrevue.com/tip/windows-installation-date/

**Comment by louisdh** [comment]
`systeminfo` is a Windows command, the close equivalent on iOS is `uname -a`. However, this doesn't show the installation, but it shows the date/time when the kernel was compiled.

**Comment by Basic-income** [comment]
there is no way to see the ios installation date? can't you extract from the installation log file in ios?

**Comment by louisdh** [comment]
I don't think so.
