### ISSUE TITLE
Can't embed dylibs in iOS app.

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#103]
Currently, `libawk.dylib`, `libcurl.dylib` and others are in the "Embedded Binaries" section of the OpenTerm project. When uploading to iTunes Connect this gives an error. Fyi: Building and running on device works fine, it's only when uploading to iTunes Connect that Apple's validation makes an issue of those dylibs.

It appears having a dylib in an iOS app is illegal at the moment:
`It's likely you have a plain dylib outside of a framework somewhere, which is only supported on macOS.` (https://forums.developer.apple.com/message/218019#218019)

@holzschu Any idea on how to fix this?

**Comment by holzschu** [comment]
Well, that is certainly frustrating. 

If I read the forums correctly, converting the dylibs to frameworks would be acceptable? If so, I'm going to have a look into it. Otherwise, it would be back to static libraries, which would work but increase the memory footprint of the app.

**Comment by louisdh** [comment]
Yes, frameworks should work. Thanks!

**Comment by holzschu** [comment]
Work in progress if you want to test: https://github.com/holzschu/ios_system/tree/experimental
(only done "files" and "tar" so far. I wish there was a way to make the process more automatic)

**Comment by holzschu** [comment]
For my information: did the dynamic libraries setup work for previous versions of OpenTerm, and stopped working because the rule is more strictly enforced, or is it that it never worked?

**Comment by louisdh** [comment]
All previous builds of OpenTerm didn't use dynamic libraries if I remember correctly. The rule has always been in place it seems.

**Comment by holzschu** [comment]
All libraries have now been transformed into frameworks: https://github.com/holzschu/ios_system/tree/experimental 
(now onto network_ios)

**Comment by louisdh** [comment]
Confirmed: now that the dylibs are frameworks, uploading builds for App Store usage works 🎉.
@holzschu Thank you so much!
