### ISSUE TITLE
💥 Crashes on pressing back button

### ISSUE THREAD

**Issue by RishabhTayal** [louisdh/terminal#114]
The app crashes when the command prompt is empty and you press back/delete button.

**Comment by RishabhTayal** [comment]
@JayantVarma please check this video: https://www.dropbox.com/s/ma2yol9f7xnsipm/IMG_0963.TRIM.MOV?dl=0

I am just pressing delete button on the keyboard.

**Comment by JayantVarma** [comment]
Yeah, I can see that it crashes on your iPhone X. 
I tried it on an iPhone 6S running OpenTerm v1.3 build 15
and iPad Pro  running OpenTerm v2.0 build 22

Which version are you running on your device? The App Store build or the newer build from the source code above?

I believe that maybe @louisdh could chime in with details on this.

**Comment by louisdh** [comment]
Should be fixed: 1c7479849b30f2847bc63919bc1bb60ad56bd102.
