### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by hevey** [louisdh/terminal#119]
After running through the install process. I am unable to install this onto a device. It appears to build fine however when trying to deploy to device I either get an "unable to write to device" error or "This application’s bundle identifier does not match its code signing identifier." This happens to both my iPad or iPhone running 11.3 
I have tried different bundle identifiers but unable to determine where the issue lies.

Attached a screenshot of xcode

<img width="2560" alt="screen shot 2018-04-15 at 10 12 50 am" src="https://user-images.githubusercontent.com/7008490/38773655-98b6ae2e-4095-11e8-9e44-2ca618e20fc1.png">

**Comment by filippocld** [comment]
Make sure you follw these steps:
1. Clone the repo
2. Run ./bootstrap.sh
3. Edit the file resign-frameworks.sh replacing louis's certificates with your certificates
4. Run ./resign-frameworks.sh
5. Open the file OpenTerm.xcworkspace
5.1. If you don’t have a paid developer subscription, got to OpenTerm/ entitlements and delete everything. You won’t be able to use icloud but you'll be able to sign.
6. Click on Openterm.xcodeproj and change the bundle identifier to a custom one
7. Select your certificates in the Team menu
8. Do the same with tests
9. Press Run

**Comment by hevey** [comment]
Thanks for the information, I missed resigning the frameworks
