### ISSUE TITLE
Shell function silently changes directory to ~

### ISSUE THREAD

**Issue by filippocld** [louisdh/terminal#123]
Steps to reproduce:
1. Make a script with the shell function. My script had the following content
`shell("ls -lar") `
2. cd to some directory 
3. Run the script
4. Run pwd and you'll see we’re back to ~

![img_9141](https://user-images.githubusercontent.com/2400384/39094907-c16e1436-4637-11e8-9d51-70bc225b88ac.png)

**Comment by filippocld** [comment]
This is so frustrating. The "bug" script just contains `shell("pwd")`
I tried with 2 `shell("pwd")` one after the other to see if the dir is changed after a single function call or at the end of the script. It looks like it's at the end of the entire script.
![img_9163](https://user-images.githubusercontent.com/2400384/39196001-5acd92c8-47e1-11e8-9033-afb3712df844.jpeg)

**Comment by louisdh** [comment]
Fixed in 7b66f22967ea162bbf3e62dc196724e701d013ae
