### ISSUE TITLE
Accepting new commands

### ISSUE THREAD

**Issue by hevey** [louisdh/terminal#128]
Just wondering will you be accepting any and all commands if built for OpenTerm. I am wanting to attempt to build some small tools as commands (in this case porting ecm tools) to be used with OpenTerm and want to know the likely hood of them being accepted?

**Comment by louisdh** [comment]
Accepting new commands is decided on a case-by-case basis. If you're wondering if a new command is likely to be merged in the official OpenTerm, it's probably best to create a new issue for that command, so I can comment on it before you put too much work in it (assuming you want it in the official OpenTerm).
