### ISSUE TITLE
Add tab completion

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#13]

**Comment by holzschu** [comment]
An easy way to do this is the linenoise library: http://github.com/antirez/linenoise

They have callbacks for completion and hints. It also handles history.

**Comment by IMcD23** [comment]
Now that autocomplete has been shipped, perhaps hitting tab should just type the first available auto completion?

**Comment by palmin** [comment]
@IMcD23 That would make a lot of sense. 

Maybe pressing tab several times could switch to the next completion?

**Comment by mecid** [comment]
https://github.com/louisdh/terminal/pull/64

**Comment by filippocld** [comment]
This issue has to be closed since the features were successfully implemented.
