### ISSUE TITLE
open-url waits for stdin, even when url passed

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#132]
For example:
```
open-url https://silverfox.be 
```

This waits for stdin. @palmin Is this a bug?
I believe something changed regarding the stdin reading in commands, which caused this issue.

**Comment by palmin** [comment]
It is wanted behavior when stdin is the result of a pipe or redirect but unwanted behavior when stdin is interactive. 

When this feature was added stdin was never interactive. Do you know of some way to know if it is one or the other?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by louisdh** [comment]
Hmm, that I don’t know. @holzschu do you have any idea on how to check for that?

**Comment by palmin** [comment]
>Hmm, that I don’t know. @holzschu do you have any idea on how to check for that?

@louisdh traditionally isatty checks for this and I will make experiments to see if this exists in ios_system and behaves as expected. I will reach out if I’m stuck.

**Comment by palmin** [comment]
The fix unfortunately requires a small change in what ios_system exposes in the public header file, but pull requests are ready for both projects.

**Comment by palmin** [comment]
@louisdh ios_system has merged in the change, which allowed me to update the submodule reference and #133 passes tests. 

Let met know if you need any more from me.
