### ISSUE TITLE
Lone quotation mark causes crash

### ISSUE THREAD

**Issue by asquared31415** [louisdh/terminal#2]
Entering a quotation mark (“) on its own into the terminal causes it to crash on execution.  It does not appear to be just an issue with it being unpaired as 123”, “123, and 12”3 work as expected.  Single quotation marks (‘) do not exhibit this issue.

I think it might be that the terminal is trying to parse the following characters into a command to run, and getting no following characters.  Things like “rm

**Comment by asquared31415** [comment]
Oops, I pressed submit too early.

I mean to continue with

Things like “rm” work properly, and the terminal is trying to execute nothing.  This might be a side effect of the strange way “ are handled (I’m submitting another issue)

**Comment by louisdh** [comment]
Should be fixed by 49ec497ad565d333bc86c91ab3c58394105c3a20. Thanks for reporting!
