### ISSUE TITLE
Pipe is not working.

### ISSUE THREAD

**Issue by stona1** [louisdh/terminal#21]
Hi,

First of all thank you for great app :)
I have problem. When type in in prompt:

`
iPad (1710): ls | wc

ls: wc: No such file or directory

ls: |: No such file or directory
`

Is ‚pipe’ supported by Terminal app?

Best regards
Arek

**Comment by holzschu** [comment]
Reading and interpreting the shell command is done in iOS_system (I'm the author), and it doesn't support pipes for the time being. I've created an issue over there: https://github.com/holzschu/ios_system/issues/6

**Comment by palmin** [comment]
Couldn't this issue be closed?

**Comment by stona1** [comment]
Yes, it should be closed :)
