### ISSUE TITLE
Can I build this without a paid developer account?

### ISSUE THREAD

**Issue by BasThomas** [louisdh/terminal#22]
Seems like this uses iCloud, and Xcode doesn't like the fact that I try to build without a paid account.

**Comment by BasThomas** [comment]
As a workaround, I removed the iCloud entitlements and capability locally, making it so I could run and test at least #24. :)

**Comment by BasThomas** [comment]
Not as far as I know.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by filippocld** [comment]
I mean, you can’t use iCloud entitlements (among others) without paying the paid developer account, but that’s an issue with Apple, not OpenTerm. If your intention was just sideloading without the iCloud entitlements i think you should close the issue :-)

**Comment by BasThomas** [comment]
Fair enough. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
