### ISSUE TITLE
x-callback-url client support

### ISSUE THREAD

**Issue by palmin** [louisdh/terminal#26]
It would be very cool to be able to invoke automation capabilities in other apps through [x-callback-url](http://x-callback-url.com) commands. 

Imagine something like
````
 grep < myfile | x-callback-url workflow://run-workflow?name=Send%20Email&input=[stdin]
````

I am not sure about the syntax yet as it requires piping to be in place.

The important thing is to find a nice way to bridge command-line pipes to x-callback-url such that it is easy to pass `stdin` as input parameters and easy to get result from `x-success` or `x-error` and put this on stdout or stderr.

I opened this issue to gauge interest. Once piping is in place I would be happy to submit a PR with the work.

**Comment by palmin** [comment]
It seems I can start working on it now: https://github.com/holzschu/ios_system/pull/10

**Comment by palmin** [comment]
I have started looking into this and it seems a `x-callback-url' command needs to run inside `ios_system` to work with pipes and redirection.

The [README](https://github.com/holzschu/ios_system/blob/master/README.md) contains instructions no how to replace existing commands with `replaceCommand` but suggests contributing directory to `ios_system` to add new commands.

Implementing `x-callback-url` requires calling out to another app with `openUrl` and waiting to receive a callback on the application delegate. It seems like something that would contaminate `ios_system` and should be kept in OpenTerminal.

@holzschu: Would you advise against using `replaceCommand` to add a brand new command?

I am a also little bit worried about control flow. The `x-callback-url` doesn't terminate until a callback has been received on the app delegate. Depending on how `ios_system` is called this can prove tricky.

**Comment by holzschu** [comment]
`replaceCommand` basically adds an element to a NSDictonary:
```
mutableDict[commandName] = [NSValue valueWithPointer: newFunction];
```
If the command does not already exist, it is simply added to the dictionary, with no side-effects. So no problems here.

Regarding the other part of the question: `ios_system` starts a new thread for each command, with communication channels between them if they are piped. Each thread has `thread_stdin` and `thread_stdout` (thread-local variables) that it writes to. The streams are closed when the thread exits. 

We wait (with `pthread_join`) for the first and last command of the command line to terminate.

**Comment by palmin** [comment]
Great. I will continue using `replaceCommand` as I have been doing in my experiments.

**Comment by palmin** [comment]
> I am a also little bit worried about control flow. The x-callback-url doesn't terminate until a callback has been received on the app delegate. Depending on how ios_system is called this can prove tricky.

This did indeed turn out to be a problem. Due to the nature of `x-callback-url` it is both asynchronous and requires the main run-loop to be serviced. 

My current problem in https://github.com/palmin/terminal/commit/68ad9f09cdfab4d9b8e8d439aa43ea7effa6423e is that `process` in `ViewController` is running on the main thread waiting for `ios_system` to complete which blocks the URL from opening.

To fix this I would need to change `process` in `ViewController` to have a callback instead of a return value. How do you feel about this @louisdh ?

**Comment by louisdh** [comment]
@palmin Changing `process` to having a callback is something that I was planning to do anyways, so feel free to do that if it's blocking you at the moment. Btw: this will require the `TerminalView` to block any text changes while it's waiting for the command output.

**Comment by palmin** [comment]
https://twitter.com/palmin/status/956165704792887296

**Comment by palmin** [comment]
Work is done and the PR merged. 😻
