### ISSUE TITLE
CA certificate issue when using curl

### ISSUE THREAD

**Issue by mathewcropper** [louisdh/terminal#34]
Hi there. When trying to use the curl command, I’m getting the following output and no result. I’ve been unable to find any reference to this issue elsewhere, so thought it best to post here.

```
Wesley: curl "https://REDACTED"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) SSL: can't load CA certificate file /var/mobile/Containers/Data/Application/FF8326DA-0265-40D5-A8C5-F0EA506EE623/Documents/cacert.pem
```

**Comment by holzschu** [comment]
That is normal behaviour for CURL, I'm afraid. You need to provide and upload your own CA certificates (cacert.pem). You can usually copy them from your main machine. CURL has a default set of root certificates: https://curl.haxx.se/docs/caextract.html

**Comment by louisdh** [comment]
I've added a default certificate to the app (880d4516ea1a9834e2873363fecc7246ab38c944).
