### ISSUE TITLE
Typing "\" before a command crashes.

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#43]

**Comment by palmin** [comment]
I have a fix for that in https://github.com/palmin/terminal/commit/4de660087a9d9e269e846e217a9ff2d5b90ab988
but I wonder if it makes more sense to just make a PR towards `ios_system` to keep down the number of pull requests?

What would you prefer?

**Comment by louisdh** [comment]
Yeah, a PR for `ios_system` is the logical thing to do.
