### ISSUE TITLE
Standardize Indentation rules

### ISSUE THREAD

**Issue by IMcD23** [louisdh/terminal#54]
Currently, both tabs & spaces are littered across the code. It'd be nice to set a standard and set project-wide Xcode settings for indentation, and add SwiftLint rules.

**Comment by louisdh** [comment]
I'm in favor of tabs, fwiw.

**Comment by louisdh** [comment]
Also: if indentation is standardized for OpenTerm, I think it should only apply to the app. `ios_system` shouldn't need to change its indentation to match OpenTerm.

**Comment by mecid** [comment]
@louisdh we can exclude ios_system folder from SwiftLint.

**Comment by louisdh** [comment]
I will add SwiftLint once #62 and #63 have been merged (to avoid further conflicts).

**Comment by louisdh** [comment]
Added Swiftlint in 0f5a1c426debf8ab47ad303bdca9b2600c29ab7e

**Comment by louisdh** [comment]
I've set the project setting for indentation to use tabs 952270e511c49d928ecdc190b72c31f4498f7852.
