### ISSUE TITLE
Directory selection with Dropbox

### ISSUE THREAD

**Issue by msroest** [louisdh/terminal#56]
I can successfully select a directory inside iCloud drive or working copy and everything works as expected.

But if I try to use a dropbox folder nothing happens.  I'm going to guess this is an issue with the dropbox files provider and not OpenTerm but wanted to report it incase something can be done.

**Comment by palmin** [comment]
This is a issue with Dropbox and it would be wonderful if they could support this, but it is outside the control of OpenTerm. 

Maybe this issue should be closed?

**Comment by louisdh** [comment]
I have improved the error handling in OpenTerm (3f826aaf5725f80d6a198f5e823419896e47864f), not much else we can do I'm afraid.
