### ISSUE TITLE
Clipboard access command

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#58]
A command that can read/write to the system's clipboard might be neat.

**Comment by IMcD23** [comment]
On top of this, perhaps adding various iOS-specific commands, such as adding calendar events, reminders, etc.

**Comment by mecid** [comment]
https://github.com/louisdh/terminal/pull/61

**Comment by filippocld** [comment]
A pull request has just been made, and there are no conflicts. The code seems good so i'd merge it

**Comment by mecid** [comment]
@filippocld i've pushed update. Commands renamed to pbcopy and pbpaste.
