### ISSUE TITLE
Too many top right bar button items on iPhone

### ISSUE THREAD

**Issue by IMcD23** [louisdh/terminal#67]
We now have 4 bar button items on the main view. We need to either create an overflow menu or hide the title.

Continuing discussion from #65.

**Comment by IMcD23** [comment]
Here's a screen cap of my current fish prompt:
<img width="531" alt="screen shot 2018-02-02 at 1 07 18 pm" src="https://user-images.githubusercontent.com/1221567/35755096-ca3d6220-081a-11e8-8d36-2c4afc8de0d9.png">

Shows username, hostname, current directory, then new line and a "↪" character.

**Comment by IMcD23** [comment]
I'll be opening a PR soon-ish with a fix for this. Here's what I've implemented:
![img_0147](https://user-images.githubusercontent.com/1221567/35773318-38e9877e-0903-11e8-8ab1-72a7cc4e18a5.PNG)
![img_7903](https://user-images.githubusercontent.com/1221567/35773319-390c52cc-0903-11e8-9d50-4dbab7a8068c.PNG)

**Comment by filippocld** [comment]
Regarding putting the current directory in every line: .bashrc and prompt customizations would be really great. That needs another issue though :-)
