### ISSUE TITLE
Support for multiple tabs

### ISSUE THREAD

**Issue by IMcD23** [louisdh/terminal#69]
I am preparing a change to support a tabbed interface, similar to macOS Terminal or iOS Safari. I'm using my own library, [TabView](https://github.com/IMcD23/TabView), to accomplish this.

There are a few architectural issues that will need fixing to support this.

- ~~Currently, we rely on FileManager.currentDirectoryPath for the terminal, which is a process-wide variable. To support multiple tabs, it's required that each tab have its own "terminal" with its own working directory.~~ On second thought, I don't believe it will be possible to have multiple concurrent working directories. It should work to switch between them when commands are run, however. This just means we can't support concurrent running commands.
- CommandExecutor supports multiple instances, but the changes being made by @holzschu to the way it calls ios_system (in PR #63), will be in conflict with that, as it changes the process-wide stdout variable._

Here's a screenshot if my current tab UI for OpenTerm:

![debbe4aa-0505-404b-97e8-046068963b65](https://user-images.githubusercontent.com/1221567/35773187-aa6e6c42-08ff-11e8-81d7-dd96dc835d72.jpeg)

**Comment by holzschu** [comment]
I notice the edits you made to that issue. I'd like to point out that running concurrent commands in iOS_system is also probably impossible for the time being, or would require substantial changes to the source of all commands. We start with the source code of BSD commands; they tend to assume they're alone in their memory space, and use a lot of global variables.

**Comment by IMcD23** [comment]
Makes sense. I'm closing this issue, as the approach I ended up taking thankfully needed no changes to ios_system.
