### ISSUE TITLE
first tab behaving weird on iPhone X

### ISSUE THREAD

**Issue by palmin** [louisdh/terminal#77]
I am working to adapt Drag and Drop to the new tabbed interface (commit 255da5f33ad8ac647d733c5190167b20fedfa9a9) and the first tab disappears above the navbar on iPhone X. 

This happens when the first tab is the only one, but also when adding a new tab. Second tab does not seem to have this problem.

![img_c1270fb2f3b3-2](https://user-images.githubusercontent.com/1230554/35913102-ec677e34-0bfe-11e8-9b88-71fcdb3bab3e.jpeg)

It was hard to get this on the screenshot but as the cursor blinks you can see a small green dot on the left side of the screen below the tab bar.

**Comment by IMcD23** [comment]
I have a hunch here. Try changing your font size in settings. Does that fix it?

**Comment by palmin** [comment]
Sorry to leave this hanging for so long.
It no longer happens e9cc4b8b429cd44314e22a9da79b9576718f72c3
