### ISSUE TITLE
Emoticons in output are not displayed correctly

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#78]
```bash
echo 😀
```

shows this as output:
```
ð
```

**Comment by louisdh** [comment]
@palmin @IMcD23 Do any of you know what might be causing this? Perhaps the ANSI text parsing?

**Comment by IMcD23** [comment]
Probably related. Try debugging through the Parser as stdout comes in, see what it does, since it parses per character. 

I’ll take a look later today as well.

**Comment by IMcD23** [comment]
It's an issue with ios_system, and I've filed an issue over there. Commands are converted to ASCII and passed into the command's main method as ASCII, thus causing unicode-only characters to break.

**Comment by louisdh** [comment]
holzschu/ios_system/issues/21

**Comment by IMcD23** [comment]
Fixed in PR #80.
