### ISSUE TITLE
Unsupported commands show up in auto complete

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#97]
Examples: `ctags`, `dig`.

When trying to use these command, the error "command not found" is shown.

@holzschu This might be a bug in ios_system?

**Comment by louisdh** [comment]
@holzschu I believe this bug was introduced with the `SIDELOADING` macro.

**Comment by louisdh** [comment]
This also includes commands like `telnet`. I suppose I should add [network_ios](https://github.com/holzschu/network_ios) to OpenTerm?

**Comment by holzschu** [comment]
Argl! Sorry! yes, you're absolutely right. Both network_ios and ctags_ios, to be precise.

So much for this being a minor release that does not require changing the Xcode project.

**Comment by louisdh** [comment]
Did you create `network_ios` in Xcode 9.3 by any chance? I'm getting an error when trying to open it in Xcode 9.2.

**Comment by holzschu** [comment]
Uh, yes. I didn't notice the incompatible change in format. I have pushed an 8.0-compatible version of the Xcode project for network_ios and ctags_ios.

**Comment by louisdh** [comment]
Thanks! I also see you're targeting iOS 11.3 in `network_ios`, would be ok to change this to 11.0?

**Comment by holzschu** [comment]
Sorry again. I need to pay more attention to settings. Fixed and pushed.

**Comment by louisdh** [comment]
Thank you! Where can I find the `ctags_ios` project? Is it open source yet?

**Comment by holzschu** [comment]
Right here: https://github.com/holzschu/ctags 
Xcode project is in `ctags/ctags.xcodeproj`

**Comment by louisdh** [comment]
I notice [ctags](https://github.com/holzschu/ctags) has a GLP-2.0 license, would this be ok to add to OpenTerm (an iOS app)?

@palmin I suppose the explanation you posted in https://github.com/louisdh/terminal/issues/59 is relevant for [ctags](https://github.com/holzschu/ctags)?

**Comment by holzschu** [comment]
Anyway, ctags is not really useful inside OpenTerm (it is really nice inside iVim, though). I moved it to inside the "#ifdef SIDELOADING" macro.

**Comment by louisdh** [comment]
Added more tests to prevent issues like this in the future: 63a510de25148c6109ceb44d307b09f9042a50ff
