### ISSUE TITLE
network_ios compile issue when targeting simulator.

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#98]
Building for the simulator currently fails: `'arm/param.h' file not found`.

@holzschu Did I forget to include something in OpenTerm? Or does network_ios not support the iOS simulator (i386)?

Build failure: https://travis-ci.org/louisdh/terminal/builds/355534669

**Comment by holzschu** [comment]
I did not include the simulator in my tests.
Fixing that one was easy: include `i386/param.h` when building for the simulator. It now compiles on my system.

**Comment by louisdh** [comment]
Thank you!
